name: Publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for OCI image to publish'
        required: true
env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-image:
    runs-on: ubuntu-24.04

    # Permissions required for publishing Docker image.
    # See https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
    permissions:
      contents: read
      packages: write

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven

        - name: Log in to the Container registry
          uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build with Maven
          run: |
            mvn --batch-mode --update-snapshots install
            mvn --batch-mode --update-snapshots spring-boot:build-image -pl org-tweetyproject-web
        - name: Set MAVEN_PROJECT_VERSION environment variable
          run: |
            echo "MAVEN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        - name: Provide image name variable
          id: lowercase_repository_name
          run: echo "::set-output name=val::${IMAGE_NAME,,}"
          env:
            IMAGE_NAME: ${{ github.repository }}
        - name: Build, tag and push Docker image
          run: |
            docker tag web:${{ env.MAVEN_PROJECT_VERSION }} ${{ env.REGISTRY }}/${{ steps.lowercase_repository_name.outputs.val }}/tweetyproject-web-server:${{ inputs.tag }}
            docker push ${{ env.REGISTRY }}/${{ steps.lowercase_repository_name.outputs.val }}/tweetyproject-web-server:${{ inputs.tag }}
